server:
  port: 8099

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fa_item_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: lahiru
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver # MySQL database config

  # JPA CONFIGURATIONS
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC

redis:
  timeout:
    auto-complete-minutes: 10
    location-minutes: 20

cloudOfGoods:
  redis:
    host: 127.0.0.1
    port: 6379

endpoints:
  food:
    url: api/food
    methods:
      post: /send
      post-smell-taste-texture-by-id: id/{foodId}/addOrUpdate/smellTasteTexture
  cooking-method:
    url: api/cooking-method
  order:
    url: /api/orders


  # Cors Allow(White List)
allow:
  headers: Content-Type,Authorization
  origin: http://localhost:3000

category:
  cache:
    name: order

#  servlet:
#    context-path: /api # Base URL for REST endpoints
#
#endpoints:
#  message: /message # Endpoint for message resource
#  notification: /products # Endpoint for notification resource